// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GPSDataProtoBuf.proto

package me.daoke.driving.entity;

public final class GPSDataProtuBuf {
  private GPSDataProtuBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LocationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required double longitude = 1;
    boolean hasLongitude();
    double getLongitude();
    
    // required double latitude = 2;
    boolean hasLatitude();
    double getLatitude();
    
    // required int32 speed = 3;
    boolean hasSpeed();
    int getSpeed();
    
    // required int32 GPSTime = 4;
    boolean hasGPSTime();
    int getGPSTime();
    
    // required sint32 altitude = 5;
    boolean hasAltitude();
    int getAltitude();
    
    // required sint32 direction = 6;
    boolean hasDirection();
    int getDirection();
  }
  public static final class Location extends
      com.google.protobuf.GeneratedMessage
      implements LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(Builder builder) {
      super(builder);
    }
    private Location(boolean noInit) {}
    
    private static final Location defaultInstance;
    public static Location getDefaultInstance() {
      return defaultInstance;
    }
    
    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GPSDataProtuBuf.internal_static_me_daoke_poweroff_entity_Location_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GPSDataProtuBuf.internal_static_me_daoke_poweroff_entity_Location_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required double longitude = 1;
    public static final int LONGITUDE_FIELD_NUMBER = 1;
    private double longitude_;
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public double getLongitude() {
      return longitude_;
    }
    
    // required double latitude = 2;
    public static final int LATITUDE_FIELD_NUMBER = 2;
    private double latitude_;
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getLatitude() {
      return latitude_;
    }
    
    // required int32 speed = 3;
    public static final int SPEED_FIELD_NUMBER = 3;
    private int speed_;
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getSpeed() {
      return speed_;
    }
    
    // required int32 GPSTime = 4;
    public static final int GPSTIME_FIELD_NUMBER = 4;
    private int gPSTime_;
    public boolean hasGPSTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getGPSTime() {
      return gPSTime_;
    }
    
    // required sint32 altitude = 5;
    public static final int ALTITUDE_FIELD_NUMBER = 5;
    private int altitude_;
    public boolean hasAltitude() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getAltitude() {
      return altitude_;
    }
    
    // required sint32 direction = 6;
    public static final int DIRECTION_FIELD_NUMBER = 6;
    private int direction_;
    public boolean hasDirection() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getDirection() {
      return direction_;
    }
    
    private void initFields() {
      longitude_ = 0D;
      latitude_ = 0D;
      speed_ = 0;
      gPSTime_ = 0;
      altitude_ = 0;
      direction_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGPSTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAltitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDirection()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, longitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, latitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, speed_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, gPSTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeSInt32(5, altitude_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeSInt32(6, direction_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, longitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, latitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, speed_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, gPSTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(5, altitude_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(6, direction_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GPSDataProtuBuf.internal_static_me_daoke_poweroff_entity_Location_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GPSDataProtuBuf.internal_static_me_daoke_poweroff_entity_Location_fieldAccessorTable;
      }
      
      // Construct using me.daoke.poweroff.entity.GPSDataProtuBuf.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        gPSTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        altitude_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        direction_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Location.getDescriptor();
      }
      
      public Location getDefaultInstanceForType() {
        return Location.getDefaultInstance();
      }
      
      public Location build() {
        Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Location buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Location buildPartial() {
        Location result = new Location(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gPSTime_ = gPSTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.altitude_ = altitude_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.direction_ = direction_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Location) {
          return mergeFrom((Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Location other) {
        if (other == Location.getDefaultInstance()) return this;
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasGPSTime()) {
          setGPSTime(other.getGPSTime());
        }
        if (other.hasAltitude()) {
          setAltitude(other.getAltitude());
        }
        if (other.hasDirection()) {
          setDirection(other.getDirection());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLongitude()) {
          
          return false;
        }
        if (!hasLatitude()) {
          
          return false;
        }
        if (!hasSpeed()) {
          
          return false;
        }
        if (!hasGPSTime()) {
          
          return false;
        }
        if (!hasAltitude()) {
          
          return false;
        }
        if (!hasDirection()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              longitude_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              latitude_ = input.readDouble();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              speed_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              gPSTime_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              altitude_ = input.readSInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              direction_ = input.readSInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required double longitude = 1;
      private double longitude_ ;
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public double getLongitude() {
        return longitude_;
      }
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000001;
        longitude_ = value;
        onChanged();
        return this;
      }
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0D;
        onChanged();
        return this;
      }
      
      // required double latitude = 2;
      private double latitude_ ;
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getLatitude() {
        return latitude_;
      }
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000002;
        latitude_ = value;
        onChanged();
        return this;
      }
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        latitude_ = 0D;
        onChanged();
        return this;
      }
      
      // required int32 speed = 3;
      private int speed_ ;
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getSpeed() {
        return speed_;
      }
      public Builder setSpeed(int value) {
        bitField0_ |= 0x00000004;
        speed_ = value;
        onChanged();
        return this;
      }
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        speed_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 GPSTime = 4;
      private int gPSTime_ ;
      public boolean hasGPSTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getGPSTime() {
        return gPSTime_;
      }
      public Builder setGPSTime(int value) {
        bitField0_ |= 0x00000008;
        gPSTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearGPSTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gPSTime_ = 0;
        onChanged();
        return this;
      }
      
      // required sint32 altitude = 5;
      private int altitude_ ;
      public boolean hasAltitude() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getAltitude() {
        return altitude_;
      }
      public Builder setAltitude(int value) {
        bitField0_ |= 0x00000010;
        altitude_ = value;
        onChanged();
        return this;
      }
      public Builder clearAltitude() {
        bitField0_ = (bitField0_ & ~0x00000010);
        altitude_ = 0;
        onChanged();
        return this;
      }
      
      // required sint32 direction = 6;
      private int direction_ ;
      public boolean hasDirection() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getDirection() {
        return direction_;
      }
      public Builder setDirection(int value) {
        bitField0_ |= 0x00000020;
        direction_ = value;
        onChanged();
        return this;
      }
      public Builder clearDirection() {
        bitField0_ = (bitField0_ & ~0x00000020);
        direction_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:me.daoke.poweroff.entity.Location)
    }
    
    static {
      defaultInstance = new Location(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:me.daoke.poweroff.entity.Location)
  }
  
  public interface GPSDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string IMEI = 1;
    boolean hasIMEI();
    String getIMEI();
    
    // required string tokenCode = 2;
    boolean hasTokenCode();
    String getTokenCode();
    
    // optional string accountID = 3;
    boolean hasAccountID();
    String getAccountID();
    
    // repeated .me.daoke.poweroff.entity.Location locations = 4;
    java.util.List<Location>
        getLocationsList();
    Location getLocations(int index);
    int getLocationsCount();
    java.util.List<? extends LocationOrBuilder>
        getLocationsOrBuilderList();
    LocationOrBuilder getLocationsOrBuilder(
            int index);
    
    // repeated .me.daoke.poweroff.entity.Location extragps = 5;
    java.util.List<Location>
        getExtragpsList();
    Location getExtragps(int index);
    int getExtragpsCount();
    java.util.List<? extends LocationOrBuilder>
        getExtragpsOrBuilderList();
    LocationOrBuilder getExtragpsOrBuilder(
            int index);
  }
  public static final class GPSData extends
      com.google.protobuf.GeneratedMessage
      implements GPSDataOrBuilder {
    // Use GPSData.newBuilder() to construct.
    private GPSData(Builder builder) {
      super(builder);
    }
    private GPSData(boolean noInit) {}
    
    private static final GPSData defaultInstance;
    public static GPSData getDefaultInstance() {
      return defaultInstance;
    }
    
    public GPSData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GPSDataProtuBuf.internal_static_me_daoke_poweroff_entity_GPSData_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GPSDataProtuBuf.internal_static_me_daoke_poweroff_entity_GPSData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string IMEI = 1;
    public static final int IMEI_FIELD_NUMBER = 1;
    private Object iMEI_;
    public boolean hasIMEI() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getIMEI() {
      Object ref = iMEI_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          iMEI_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIMEIBytes() {
      Object ref = iMEI_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        iMEI_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string tokenCode = 2;
    public static final int TOKENCODE_FIELD_NUMBER = 2;
    private Object tokenCode_;
    public boolean hasTokenCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTokenCode() {
      Object ref = tokenCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          tokenCode_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTokenCodeBytes() {
      Object ref = tokenCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        tokenCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string accountID = 3;
    public static final int ACCOUNTID_FIELD_NUMBER = 3;
    private Object accountID_;
    public boolean hasAccountID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getAccountID() {
      Object ref = accountID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          accountID_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccountIDBytes() {
      Object ref = accountID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        accountID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .me.daoke.poweroff.entity.Location locations = 4;
    public static final int LOCATIONS_FIELD_NUMBER = 4;
    private java.util.List<Location> locations_;
    public java.util.List<Location> getLocationsList() {
      return locations_;
    }
    public java.util.List<? extends LocationOrBuilder>
        getLocationsOrBuilderList() {
      return locations_;
    }
    public int getLocationsCount() {
      return locations_.size();
    }
    public Location getLocations(int index) {
      return locations_.get(index);
    }
    public LocationOrBuilder getLocationsOrBuilder(
        int index) {
      return locations_.get(index);
    }
    
    // repeated .me.daoke.poweroff.entity.Location extragps = 5;
    public static final int EXTRAGPS_FIELD_NUMBER = 5;
    private java.util.List<Location> extragps_;
    public java.util.List<Location> getExtragpsList() {
      return extragps_;
    }
    public java.util.List<? extends LocationOrBuilder>
        getExtragpsOrBuilderList() {
      return extragps_;
    }
    public int getExtragpsCount() {
      return extragps_.size();
    }
    public Location getExtragps(int index) {
      return extragps_.get(index);
    }
    public LocationOrBuilder getExtragpsOrBuilder(
        int index) {
      return extragps_.get(index);
    }
    
    private void initFields() {
      iMEI_ = "";
      tokenCode_ = "";
      accountID_ = "";
      locations_ = java.util.Collections.emptyList();
      extragps_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTokenCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getLocationsCount(); i++) {
        if (!getLocations(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getExtragpsCount(); i++) {
        if (!getExtragps(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIMEIBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTokenCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAccountIDBytes());
      }
      for (int i = 0; i < locations_.size(); i++) {
        output.writeMessage(4, locations_.get(i));
      }
      for (int i = 0; i < extragps_.size(); i++) {
        output.writeMessage(5, extragps_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIMEIBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTokenCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAccountIDBytes());
      }
      for (int i = 0; i < locations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, locations_.get(i));
      }
      for (int i = 0; i < extragps_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, extragps_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static GPSData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static GPSData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static GPSData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static GPSData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static GPSData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static GPSData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static GPSData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static GPSData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static GPSData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static GPSData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(GPSData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements GPSDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GPSDataProtuBuf.internal_static_me_daoke_poweroff_entity_GPSData_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GPSDataProtuBuf.internal_static_me_daoke_poweroff_entity_GPSData_fieldAccessorTable;
      }
      
      // Construct using me.daoke.poweroff.entity.GPSDataProtuBuf.GPSData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLocationsFieldBuilder();
          getExtragpsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        iMEI_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        tokenCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        accountID_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (locationsBuilder_ == null) {
          locations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          locationsBuilder_.clear();
        }
        if (extragpsBuilder_ == null) {
          extragps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          extragpsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GPSData.getDescriptor();
      }
      
      public GPSData getDefaultInstanceForType() {
        return GPSData.getDefaultInstance();
      }
      
      public GPSData build() {
        GPSData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private GPSData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        GPSData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public GPSData buildPartial() {
        GPSData result = new GPSData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.iMEI_ = iMEI_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tokenCode_ = tokenCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.accountID_ = accountID_;
        if (locationsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            locations_ = java.util.Collections.unmodifiableList(locations_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.locations_ = locations_;
        } else {
          result.locations_ = locationsBuilder_.build();
        }
        if (extragpsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            extragps_ = java.util.Collections.unmodifiableList(extragps_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.extragps_ = extragps_;
        } else {
          result.extragps_ = extragpsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GPSData) {
          return mergeFrom((GPSData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(GPSData other) {
        if (other == GPSData.getDefaultInstance()) return this;
        if (other.hasIMEI()) {
          setIMEI(other.getIMEI());
        }
        if (other.hasTokenCode()) {
          setTokenCode(other.getTokenCode());
        }
        if (other.hasAccountID()) {
          setAccountID(other.getAccountID());
        }
        if (locationsBuilder_ == null) {
          if (!other.locations_.isEmpty()) {
            if (locations_.isEmpty()) {
              locations_ = other.locations_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureLocationsIsMutable();
              locations_.addAll(other.locations_);
            }
            onChanged();
          }
        } else {
          if (!other.locations_.isEmpty()) {
            if (locationsBuilder_.isEmpty()) {
              locationsBuilder_.dispose();
              locationsBuilder_ = null;
              locations_ = other.locations_;
              bitField0_ = (bitField0_ & ~0x00000008);
              locationsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLocationsFieldBuilder() : null;
            } else {
              locationsBuilder_.addAllMessages(other.locations_);
            }
          }
        }
        if (extragpsBuilder_ == null) {
          if (!other.extragps_.isEmpty()) {
            if (extragps_.isEmpty()) {
              extragps_ = other.extragps_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureExtragpsIsMutable();
              extragps_.addAll(other.extragps_);
            }
            onChanged();
          }
        } else {
          if (!other.extragps_.isEmpty()) {
            if (extragpsBuilder_.isEmpty()) {
              extragpsBuilder_.dispose();
              extragpsBuilder_ = null;
              extragps_ = other.extragps_;
              bitField0_ = (bitField0_ & ~0x00000010);
              extragpsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getExtragpsFieldBuilder() : null;
            } else {
              extragpsBuilder_.addAllMessages(other.extragps_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTokenCode()) {
          
          return false;
        }
        for (int i = 0; i < getLocationsCount(); i++) {
          if (!getLocations(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getExtragpsCount(); i++) {
          if (!getExtragps(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              iMEI_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              tokenCode_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              accountID_ = input.readBytes();
              break;
            }
            case 34: {
              Location.Builder subBuilder = Location.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addLocations(subBuilder.buildPartial());
              break;
            }
            case 42: {
              Location.Builder subBuilder = Location.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addExtragps(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string IMEI = 1;
      private Object iMEI_ = "";
      public boolean hasIMEI() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getIMEI() {
        Object ref = iMEI_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          iMEI_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIMEI(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        iMEI_ = value;
        onChanged();
        return this;
      }
      public Builder clearIMEI() {
        bitField0_ = (bitField0_ & ~0x00000001);
        iMEI_ = getDefaultInstance().getIMEI();
        onChanged();
        return this;
      }
      void setIMEI(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        iMEI_ = value;
        onChanged();
      }
      
      // required string tokenCode = 2;
      private Object tokenCode_ = "";
      public boolean hasTokenCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTokenCode() {
        Object ref = tokenCode_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          tokenCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTokenCode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        tokenCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearTokenCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tokenCode_ = getDefaultInstance().getTokenCode();
        onChanged();
        return this;
      }
      void setTokenCode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        tokenCode_ = value;
        onChanged();
      }
      
      // optional string accountID = 3;
      private Object accountID_ = "";
      public boolean hasAccountID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getAccountID() {
        Object ref = accountID_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          accountID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccountID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        accountID_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccountID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        accountID_ = getDefaultInstance().getAccountID();
        onChanged();
        return this;
      }
      void setAccountID(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        accountID_ = value;
        onChanged();
      }
      
      // repeated .me.daoke.poweroff.entity.Location locations = 4;
      private java.util.List<Location> locations_ =
        java.util.Collections.emptyList();
      private void ensureLocationsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          locations_ = new java.util.ArrayList<Location>(locations_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          Location, Location.Builder, LocationOrBuilder> locationsBuilder_;
      
      public java.util.List<Location> getLocationsList() {
        if (locationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(locations_);
        } else {
          return locationsBuilder_.getMessageList();
        }
      }
      public int getLocationsCount() {
        if (locationsBuilder_ == null) {
          return locations_.size();
        } else {
          return locationsBuilder_.getCount();
        }
      }
      public Location getLocations(int index) {
        if (locationsBuilder_ == null) {
          return locations_.get(index);
        } else {
          return locationsBuilder_.getMessage(index);
        }
      }
      public Builder setLocations(
          int index, Location value) {
        if (locationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationsIsMutable();
          locations_.set(index, value);
          onChanged();
        } else {
          locationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setLocations(
          int index, Location.Builder builderForValue) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.set(index, builderForValue.build());
          onChanged();
        } else {
          locationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addLocations(Location value) {
        if (locationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationsIsMutable();
          locations_.add(value);
          onChanged();
        } else {
          locationsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addLocations(
          int index, Location value) {
        if (locationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationsIsMutable();
          locations_.add(index, value);
          onChanged();
        } else {
          locationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addLocations(
          Location.Builder builderForValue) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.add(builderForValue.build());
          onChanged();
        } else {
          locationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addLocations(
          int index, Location.Builder builderForValue) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.add(index, builderForValue.build());
          onChanged();
        } else {
          locationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllLocations(
          Iterable<? extends Location> values) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          super.addAll(values, locations_);
          onChanged();
        } else {
          locationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearLocations() {
        if (locationsBuilder_ == null) {
          locations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          locationsBuilder_.clear();
        }
        return this;
      }
      public Builder removeLocations(int index) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.remove(index);
          onChanged();
        } else {
          locationsBuilder_.remove(index);
        }
        return this;
      }
      public Location.Builder getLocationsBuilder(
          int index) {
        return getLocationsFieldBuilder().getBuilder(index);
      }
      public LocationOrBuilder getLocationsOrBuilder(
          int index) {
        if (locationsBuilder_ == null) {
          return locations_.get(index);  } else {
          return locationsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends LocationOrBuilder>
           getLocationsOrBuilderList() {
        if (locationsBuilder_ != null) {
          return locationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(locations_);
        }
      }
      public Location.Builder addLocationsBuilder() {
        return getLocationsFieldBuilder().addBuilder(
            Location.getDefaultInstance());
      }
      public Location.Builder addLocationsBuilder(
          int index) {
        return getLocationsFieldBuilder().addBuilder(
            index, Location.getDefaultInstance());
      }
      public java.util.List<Location.Builder>
           getLocationsBuilderList() {
        return getLocationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Location, Location.Builder, LocationOrBuilder>
          getLocationsFieldBuilder() {
        if (locationsBuilder_ == null) {
          locationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Location, Location.Builder, LocationOrBuilder>(
                  locations_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          locations_ = null;
        }
        return locationsBuilder_;
      }
      
      // repeated .me.daoke.poweroff.entity.Location extragps = 5;
      private java.util.List<Location> extragps_ =
        java.util.Collections.emptyList();
      private void ensureExtragpsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          extragps_ = new java.util.ArrayList<Location>(extragps_);
          bitField0_ |= 0x00000010;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          Location, Location.Builder, LocationOrBuilder> extragpsBuilder_;
      
      public java.util.List<Location> getExtragpsList() {
        if (extragpsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(extragps_);
        } else {
          return extragpsBuilder_.getMessageList();
        }
      }
      public int getExtragpsCount() {
        if (extragpsBuilder_ == null) {
          return extragps_.size();
        } else {
          return extragpsBuilder_.getCount();
        }
      }
      public Location getExtragps(int index) {
        if (extragpsBuilder_ == null) {
          return extragps_.get(index);
        } else {
          return extragpsBuilder_.getMessage(index);
        }
      }
      public Builder setExtragps(
          int index, Location value) {
        if (extragpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtragpsIsMutable();
          extragps_.set(index, value);
          onChanged();
        } else {
          extragpsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setExtragps(
          int index, Location.Builder builderForValue) {
        if (extragpsBuilder_ == null) {
          ensureExtragpsIsMutable();
          extragps_.set(index, builderForValue.build());
          onChanged();
        } else {
          extragpsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addExtragps(Location value) {
        if (extragpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtragpsIsMutable();
          extragps_.add(value);
          onChanged();
        } else {
          extragpsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addExtragps(
          int index, Location value) {
        if (extragpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtragpsIsMutable();
          extragps_.add(index, value);
          onChanged();
        } else {
          extragpsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addExtragps(
          Location.Builder builderForValue) {
        if (extragpsBuilder_ == null) {
          ensureExtragpsIsMutable();
          extragps_.add(builderForValue.build());
          onChanged();
        } else {
          extragpsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addExtragps(
          int index, Location.Builder builderForValue) {
        if (extragpsBuilder_ == null) {
          ensureExtragpsIsMutable();
          extragps_.add(index, builderForValue.build());
          onChanged();
        } else {
          extragpsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllExtragps(
          Iterable<? extends Location> values) {
        if (extragpsBuilder_ == null) {
          ensureExtragpsIsMutable();
          super.addAll(values, extragps_);
          onChanged();
        } else {
          extragpsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearExtragps() {
        if (extragpsBuilder_ == null) {
          extragps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          extragpsBuilder_.clear();
        }
        return this;
      }
      public Builder removeExtragps(int index) {
        if (extragpsBuilder_ == null) {
          ensureExtragpsIsMutable();
          extragps_.remove(index);
          onChanged();
        } else {
          extragpsBuilder_.remove(index);
        }
        return this;
      }
      public Location.Builder getExtragpsBuilder(
          int index) {
        return getExtragpsFieldBuilder().getBuilder(index);
      }
      public LocationOrBuilder getExtragpsOrBuilder(
          int index) {
        if (extragpsBuilder_ == null) {
          return extragps_.get(index);  } else {
          return extragpsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends LocationOrBuilder>
           getExtragpsOrBuilderList() {
        if (extragpsBuilder_ != null) {
          return extragpsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(extragps_);
        }
      }
      public Location.Builder addExtragpsBuilder() {
        return getExtragpsFieldBuilder().addBuilder(
            Location.getDefaultInstance());
      }
      public Location.Builder addExtragpsBuilder(
          int index) {
        return getExtragpsFieldBuilder().addBuilder(
            index, Location.getDefaultInstance());
      }
      public java.util.List<Location.Builder>
           getExtragpsBuilderList() {
        return getExtragpsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Location, Location.Builder, LocationOrBuilder>
          getExtragpsFieldBuilder() {
        if (extragpsBuilder_ == null) {
          extragpsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Location, Location.Builder, LocationOrBuilder>(
                  extragps_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          extragps_ = null;
        }
        return extragpsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:me.daoke.poweroff.entity.GPSData)
    }
    
    static {
      defaultInstance = new GPSData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:me.daoke.poweroff.entity.GPSData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_me_daoke_poweroff_entity_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_me_daoke_poweroff_entity_Location_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_me_daoke_poweroff_entity_GPSData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_me_daoke_poweroff_entity_GPSData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025GPSDataProtoBuf.proto\022\030me.daoke.powero" +
      "ff.entity\"t\n\010Location\022\021\n\tlongitude\030\001 \002(\001" +
      "\022\020\n\010latitude\030\002 \002(\001\022\r\n\005speed\030\003 \002(\005\022\017\n\007GPS" +
      "Time\030\004 \002(\005\022\020\n\010altitude\030\005 \002(\021\022\021\n\tdirectio" +
      "n\030\006 \002(\021\"\252\001\n\007GPSData\022\014\n\004IMEI\030\001 \001(\t\022\021\n\ttok" +
      "enCode\030\002 \002(\t\022\021\n\taccountID\030\003 \001(\t\0225\n\tlocat" +
      "ions\030\004 \003(\0132\".me.daoke.poweroff.entity.Lo" +
      "cation\0224\n\010extragps\030\005 \003(\0132\".me.daoke.powe" +
      "roff.entity.LocationB+\n\030me.daoke.powerof" +
      "f.entityB\017GPSDataProtuBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_me_daoke_poweroff_entity_Location_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_me_daoke_poweroff_entity_Location_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_me_daoke_poweroff_entity_Location_descriptor,
              new String[] { "Longitude", "Latitude", "Speed", "GPSTime", "Altitude", "Direction", },
              Location.class,
              Location.Builder.class);
          internal_static_me_daoke_poweroff_entity_GPSData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_me_daoke_poweroff_entity_GPSData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_me_daoke_poweroff_entity_GPSData_descriptor,
              new String[] { "IMEI", "TokenCode", "AccountID", "Locations", "Extragps", },
              GPSData.class,
              GPSData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
