// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PowerOffClientProtoBuf.proto

package me.daoke.driving.entity;

public final class PowerOffClientProtoBuf {
  private PowerOffClientProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KeyValueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 normal = 1;
    boolean hasNormal();
    int getNormal();
    
    // required string tokenCode = 2;
    boolean hasTokenCode();
    String getTokenCode();
    
    // optional string accountID = 3;
    boolean hasAccountID();
    String getAccountID();
    
    // optional string imei = 4;
    boolean hasImei();
    String getImei();
    
    // optional string travelID = 5;
    boolean hasTravelID();
    String getTravelID();
  }
  public static final class KeyValue extends
      com.google.protobuf.GeneratedMessage
      implements KeyValueOrBuilder {
    // Use KeyValue.newBuilder() to construct.
    private KeyValue(Builder builder) {
      super(builder);
    }
    private KeyValue(boolean noInit) {}
    
    private static final KeyValue defaultInstance;
    public static KeyValue getDefaultInstance() {
      return defaultInstance;
    }
    
    public KeyValue getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PowerOffClientProtoBuf.internal_static_me_daoke_poweroff_entity_KeyValue_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PowerOffClientProtoBuf.internal_static_me_daoke_poweroff_entity_KeyValue_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 normal = 1;
    public static final int NORMAL_FIELD_NUMBER = 1;
    private int normal_;
    public boolean hasNormal() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getNormal() {
      return normal_;
    }
    
    // required string tokenCode = 2;
    public static final int TOKENCODE_FIELD_NUMBER = 2;
    private Object tokenCode_;
    public boolean hasTokenCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTokenCode() {
      Object ref = tokenCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          tokenCode_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTokenCodeBytes() {
      Object ref = tokenCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        tokenCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string accountID = 3;
    public static final int ACCOUNTID_FIELD_NUMBER = 3;
    private Object accountID_;
    public boolean hasAccountID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getAccountID() {
      Object ref = accountID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          accountID_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccountIDBytes() {
      Object ref = accountID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        accountID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string imei = 4;
    public static final int IMEI_FIELD_NUMBER = 4;
    private Object imei_;
    public boolean hasImei() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getImei() {
      Object ref = imei_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          imei_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getImeiBytes() {
      Object ref = imei_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        imei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string travelID = 5;
    public static final int TRAVELID_FIELD_NUMBER = 5;
    private Object travelID_;
    public boolean hasTravelID() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getTravelID() {
      Object ref = travelID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          travelID_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTravelIDBytes() {
      Object ref = travelID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        travelID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      normal_ = 0;
      tokenCode_ = "";
      accountID_ = "";
      imei_ = "";
      travelID_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNormal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTokenCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, normal_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTokenCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAccountIDBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getImeiBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getTravelIDBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, normal_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTokenCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAccountIDBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getImeiBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getTravelIDBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static KeyValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static KeyValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static KeyValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static KeyValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static KeyValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static KeyValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static KeyValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static KeyValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static KeyValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static KeyValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(KeyValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements KeyValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PowerOffClientProtoBuf.internal_static_me_daoke_poweroff_entity_KeyValue_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PowerOffClientProtoBuf.internal_static_me_daoke_poweroff_entity_KeyValue_fieldAccessorTable;
      }
      
      // Construct using me.daoke.poweroff.entity.PowerOffClientProtoBuf.KeyValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        normal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        tokenCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        accountID_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        imei_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        travelID_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return KeyValue.getDescriptor();
      }
      
      public KeyValue getDefaultInstanceForType() {
        return KeyValue.getDefaultInstance();
      }
      
      public KeyValue build() {
        KeyValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private KeyValue buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        KeyValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public KeyValue buildPartial() {
        KeyValue result = new KeyValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.normal_ = normal_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tokenCode_ = tokenCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.accountID_ = accountID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.imei_ = imei_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.travelID_ = travelID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof KeyValue) {
          return mergeFrom((KeyValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(KeyValue other) {
        if (other == KeyValue.getDefaultInstance()) return this;
        if (other.hasNormal()) {
          setNormal(other.getNormal());
        }
        if (other.hasTokenCode()) {
          setTokenCode(other.getTokenCode());
        }
        if (other.hasAccountID()) {
          setAccountID(other.getAccountID());
        }
        if (other.hasImei()) {
          setImei(other.getImei());
        }
        if (other.hasTravelID()) {
          setTravelID(other.getTravelID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNormal()) {
          
          return false;
        }
        if (!hasTokenCode()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              normal_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              tokenCode_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              accountID_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              imei_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              travelID_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 normal = 1;
      private int normal_ ;
      public boolean hasNormal() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getNormal() {
        return normal_;
      }
      public Builder setNormal(int value) {
        bitField0_ |= 0x00000001;
        normal_ = value;
        onChanged();
        return this;
      }
      public Builder clearNormal() {
        bitField0_ = (bitField0_ & ~0x00000001);
        normal_ = 0;
        onChanged();
        return this;
      }
      
      // required string tokenCode = 2;
      private Object tokenCode_ = "";
      public boolean hasTokenCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTokenCode() {
        Object ref = tokenCode_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          tokenCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTokenCode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        tokenCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearTokenCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tokenCode_ = getDefaultInstance().getTokenCode();
        onChanged();
        return this;
      }
      void setTokenCode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        tokenCode_ = value;
        onChanged();
      }
      
      // optional string accountID = 3;
      private Object accountID_ = "";
      public boolean hasAccountID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getAccountID() {
        Object ref = accountID_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          accountID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccountID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        accountID_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccountID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        accountID_ = getDefaultInstance().getAccountID();
        onChanged();
        return this;
      }
      void setAccountID(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        accountID_ = value;
        onChanged();
      }
      
      // optional string imei = 4;
      private Object imei_ = "";
      public boolean hasImei() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getImei() {
        Object ref = imei_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          imei_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setImei(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        imei_ = value;
        onChanged();
        return this;
      }
      public Builder clearImei() {
        bitField0_ = (bitField0_ & ~0x00000008);
        imei_ = getDefaultInstance().getImei();
        onChanged();
        return this;
      }
      void setImei(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        imei_ = value;
        onChanged();
      }
      
      // optional string travelID = 5;
      private Object travelID_ = "";
      public boolean hasTravelID() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getTravelID() {
        Object ref = travelID_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          travelID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTravelID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        travelID_ = value;
        onChanged();
        return this;
      }
      public Builder clearTravelID() {
        bitField0_ = (bitField0_ & ~0x00000010);
        travelID_ = getDefaultInstance().getTravelID();
        onChanged();
        return this;
      }
      void setTravelID(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        travelID_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:me.daoke.poweroff.entity.KeyValue)
    }
    
    static {
      defaultInstance = new KeyValue(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:me.daoke.poweroff.entity.KeyValue)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_me_daoke_poweroff_entity_KeyValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_me_daoke_poweroff_entity_KeyValue_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034PowerOffClientProtoBuf.proto\022\030me.daoke" +
      ".poweroff.entity\"`\n\010KeyValue\022\016\n\006normal\030\001" +
      " \002(\005\022\021\n\ttokenCode\030\002 \002(\t\022\021\n\taccountID\030\003 \001" +
      "(\t\022\014\n\004imei\030\004 \001(\t\022\020\n\010travelID\030\005 \001(\tB2\n\030me" +
      ".daoke.poweroff.entityB\026PowerOffClientPr" +
      "otoBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_me_daoke_poweroff_entity_KeyValue_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_me_daoke_poweroff_entity_KeyValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_me_daoke_poweroff_entity_KeyValue_descriptor,
              new String[] { "Normal", "TokenCode", "AccountID", "Imei", "TravelID", },
              KeyValue.class,
              KeyValue.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
